# Makefile

exe = julia.x

#========  settings for MatFile =================
ifeq (1,1)
	# binary mode
    MatPath = ../../MatFile_linux/
    MatCompile = -I $(MatPath) matsave.cu -D MATFILE_BINARY 
    MatLink = -I $(MatPath) -Xcompiler \"-Wl,-rpath,$(MatPath)bin/\" -L$(MatPath)bin/ -l mat -l mx
else
	# text mode
    MatCompile = -DMATFILE_PRECISION=8
endif
#================================================

source = julia.cu nr3plus.cu matsave.cu

objects = $(source:.cu=.o)

compiler = nvcc

flags =  -arch=sm_60 -O3 -std=c++11 
# -g -O3

$(exe):$(objects)
	$(compiler) -o $(exe) $(flags) $(objects) $(MatLink)

$(objects):$(source)
	$(compiler) -c $(flags) $(source) $(MatCompile) 

# clean all except source
clean:
	rm -f *.o *.x *.gch *.mat *.matt Data/*.mat Data/*.matt
